[tool.ruff]
target-version = "py311"
line-length = 100
lint.select = ["E","F","I","UP","B","C4","SIM","PL","RUF"]
lint.ignore = ["E501"]  # łamanie linii zostaw formatterowi
exclude = ["alembic"]

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true
